# Generated by Django 5.2.5 on 2025-08-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentEaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='square_footage',
            field=models.TextField(default=''),
        ),
    ]
