# Generated by Django 4.2.11 on 2025-11-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentEaseApp', '0002_offer_price_offer_square_footage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='additional_utilities',
            field=models.TextField(blank=True, help_text='Additional utilities (electricity, water, etc.) - text or amount'),
        ),
        migrations.AddField(
            model_name='offer',
            name='admin_fees',
            field=models.IntegerField(blank=True, help_text='Admin fees / Maintenance in currency units', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='area',
            field=models.IntegerField(blank=True, help_text='Area in m²', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='balcony_terrace_garden',
            field=models.CharField(blank=True, choices=[('Balcony', 'Balcony'), ('Terrace', 'Terrace'), ('Garden', 'Garden'), ('None', 'None')], max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='basement',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='building_type',
            field=models.CharField(blank=True, choices=[('Apartment building', 'Apartment building'), ('Tenement house', 'Tenement house'), ('Townhouse', 'Townhouse'), ('Detached house', 'Detached house')], max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Renovated', 'Renovated'), ('Good', 'Good'), ('Needs renovation', 'Needs renovation')], max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='deposit',
            field=models.IntegerField(blank=True, help_text='Deposit in currency units', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='elevator',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='floor',
            field=models.CharField(blank=True, help_text="Floor number or 'Ground'", max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='furnished',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Partially', 'Partially')], max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='heating',
            field=models.CharField(blank=True, choices=[('Central', 'Central'), ('Gas', 'Gas'), ('Electric', 'Electric'), ('Underfloor', 'Underfloor'), ('None', 'None')], max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='internet_fiber',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.CharField(blank=True, help_text='City, District, Neighborhood', max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='minimum_rental_period',
            field=models.IntegerField(blank=True, help_text='Minimum rental period in months', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='parking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Garage', 'Garage'), ('Street', 'Street')], max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='pets_allowed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='sale_or_rent',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Rent', 'Rent')], default='Rent', max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(blank=True, help_text='Price in currency units', null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='square_footage',
            field=models.TextField(blank=True, default=''),
        ),
    ]
