# Generated by Django 4.2.11 on 2025-11-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentEaseApp', '0003_offer_additional_utilities_offer_admin_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Under negotiation', 'Under negotiation'), ('Reserved', 'Reserved'), ('Unactive', 'Unactive')], default='Available', max_length=50),
        ),
    ]
