# Generated by Django 4.2.11 on 2025-11-25 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentEaseApp', '0004_alter_offer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_landlord', to='RentEaseApp.landlorduser')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='Tenant who rented/bought this offer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_offers', to='RentEaseApp.tenantuser'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Under negotiation', 'Under negotiation'), ('Reserved', 'Reserved'), ('Unavailable', 'Unavailable'), ('Unactive', 'Unactive')], default='Available', max_length=50),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField(help_text='ID of sender (LandlordUser or TenantUser)')),
                ('sender_type', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant')], help_text='Type of sender', max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='RentEaseApp.conversation')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='RentEaseApp.offer'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_tenant', to='RentEaseApp.tenantuser'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('offer', 'landlord', 'tenant')},
        ),
    ]
