# Generated by Django 4.2.11 on 2025-11-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentEaseApp', '0005_conversation_offer_assigned_user_alter_offer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_by_landlord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='read_by_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
