# Generated by Django 4.2.11 on 2026-01-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentEaseApp', '0006_message_read_by_landlord_message_read_by_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='RentEaseApp.offer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='RentEaseApp.tenantuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'offer')},
            },
        ),
    ]
