# Generated by Django 4.2.11 on 2026-01-12 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentEaseApp', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlorduser',
            name='address_city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landlorduser',
            name='address_street',
            field=models.CharField(blank=True, help_text='Street address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landlorduser',
            name='address_zip_code',
            field=models.CharField(blank=True, help_text='ZIP/Postal code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='landlorduser',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number for rent payments', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landlorduser',
            name='id_card_number',
            field=models.CharField(blank=True, help_text='Numer Dowodu Osobistego', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='landlorduser',
            name='pesel',
            field=models.CharField(blank=True, help_text='Personal Identification Number (PESEL)', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='landlorduser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='address_city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='address_street',
            field=models.CharField(blank=True, help_text='Street address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='address_zip_code',
            field=models.CharField(blank=True, help_text='ZIP/Postal code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number for deposit return', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='id_card_number',
            field=models.CharField(blank=True, help_text='Numer Dowodu Osobistego', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='pesel',
            field=models.CharField(blank=True, help_text='Personal Identification Number (PESEL)', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_content', models.TextField(help_text='Contract template with placeholders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='RentEaseApp.landlorduser')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='RentEaseApp.offer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='RentEaseApp.tenantuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
