# Generated by Django 4.2.11 on 2026-01-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentEaseApp', '0008_landlorduser_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='final_content',
            field=models.TextField(blank=True, help_text='Final contract with all placeholders replaced'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_landlord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_tenant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('offer', 'tenant')},
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_content', models.TextField(help_text='Contract template with placeholders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_templates', to='RentEaseApp.landlorduser')),
                ('offers', models.ManyToManyField(help_text='Offers this template is assigned to', related_name='contract_templates', to='RentEaseApp.offer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='contract',
            name='template_content',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contracts', to='RentEaseApp.contracttemplate'),
        ),
    ]
