# Generated by Django 4.2.11 on 2026-01-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentEaseApp', '0009_contract_final_content_contract_signed_by_landlord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed_by_landlord_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when landlord signed', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_tenant_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when tenant signed', null=True),
        ),
    ]
