# Generated by Django 4.2.11 on 2026-01-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentEaseApp', '0010_contract_signed_by_landlord_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='template_structure',
            field=models.JSONField(blank=True, help_text='Structured template data with blocks', null=True),
        ),
    ]
