from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainSite, name="offers"),
    path('login', views.loginPanel, name="login"),
    path('register', views.registerPanel, name="register"),
    path('logout', views.logout, name="logout"),
    path('my-offers', views.my_offers, name="my_offers"),
    path('offers/create', views.create_offer, name="create_offer"),
    path('offers/<int:offer_id>', views.offer_detail, name="offer_detail"),
    path('offers/<int:offer_id>/edit', views.edit_offer, name="edit_offer"),
    path('offers/<int:offer_id>/delete', views.delete_offer, name="delete_offer"),
    path('profile', views.profile, name="profile"),
    path('profile', views.profile, name="profile"),
    path('conversations', views.conversations_list, name="conversations_list"),
    path('conversations/<int:conversation_id>', views.conversation_detail, name="conversation_detail"),
    path('conversations/offer/<int:offer_id>', views.conversation_detail_from_offer, name="conversation_detail_from_offer"),
    path('offers/<int:offer_id>/start-conversation', views.create_conversation, name="create_conversation"),
    path('conversations/<int:conversation_id>/finalize', views.assign_tenant_to_offer, name="assign_tenant_to_offer"),
    path('notifications', views.get_notifications, name="get_notifications"),
    path('conversations/<int:conversation_id>/mark-read', views.mark_messages_as_read, name="mark_messages_as_read"),
    path('api/favorites/<int:offer_id>', views.toggle_favorite, name="toggle_favorite"),
    path('api/favorites', views.get_favorites, name="get_favorites"),
    path('favorites', views.favorites_page, name="favorites"),
    path('contracts/create', views.create_contract, name="create_contract"),
    path('contracts/edit/<int:template_id>', views.create_contract, name="edit_contract_template"),
    path('contracts/manage', views.manage_contracts, name="manage_contracts"),
    path('contracts/delete/<int:template_id>', views.delete_contract_template, name="delete_contract_template"),
    path('contracts/my-contracts', views.my_contracts, name="my_contracts"),
    path('contracts/view/<int:contract_id>', views.view_contract, name="view_contract"),
    path('contracts/view/<int:contract_id>/landlord', views.view_contract_landlord, name="view_contract_landlord"),
    path('contracts/download/<int:contract_id>/pdf', views.download_contract_pdf, name="download_contract_pdf"),
    path('contracts/sign/<int:contract_id>/<str:signer_type>', views.sign_contract, name="sign_contract"),
    path('api/contracts/preview', views.preview_contract, name="preview_contract"),
    path('api/contracts/preview-pdf', views.preview_contract_pdf, name="preview_contract_pdf"),
    path('conversations/<int:conversation_id>/rent', views.rent_finalize, name="rent_finalize"),
    path('conversations/<int:conversation_id>/rent-external', views.rent_finalize_external, name="rent_finalize_external"),
]